name: PHP Composer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Files
        run: ls -alh

      - name: Install Vendor Packages
        run: COMPOSER=composer-phpunit.json && composer update

      - name: Start Tests
        run: ./vendor/bin/phpunit
