name: PHP Composer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Composer
        uses: php-actions/composer@v5

      - name: List Files
        run: ls -alh

      - name: Make vendor Dir
        run: mkdir vendor

      - name: Permission
        run: chmod 777 vendor

      - name: Install Vendor Packages
        run: COMPOSER=composer-phpunit.json && composer update

      - name: Start Tests
        run: ./vendor/bin/phpunit
